export const semesters = [
  {
    number: 1,
    subjects: [
      {
        code: "CS101",
        name: "Introduction to Programming",
        cie1: 45,
        cie2: 42,
        cie3: 48,
        ese: 50,
        average: 45,
      },
      {
        code: "MA101",
        name: "Engineering Mathematics",
        cie1: 38,
        cie2: 43,
        cie3: 41,
        ese: 50,
        average: 40.67,
      },
      {
        code: "PH101",
        name: "Engineering Physics",
        cie1: 40,
        cie2: 39,
        cie3: 44,
        ese: 50,
        average: 41,
      },
    ],
  },
  {
    number: 2,
    subjects: [
      {
        code: "CS201",
        name: "Data Structures",
        cie1: 43,
        cie2: 46,
        cie3: 44,
        ese: 50,
        average: 44.33,
      },
      {
        code: "CS202",
        name: "Digital Design",
        cie1: 41,
        cie2: 38,
        cie3: 45,
        ese: 50,
        average: 41.33,
      },
      {
        code: "MA201",
        name: "Discrete Mathematics",
        cie1: 39,
        cie2: 42,
        cie3: 40,
        ese: 50,
        average: 40.33,
      },
    ],
  },
];
